-- MySQL Script generated by MySQL Workbench
-- mer. 18 juil. 2018 12:17:15 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDD_INTER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDD_INTER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDD_INTER` DEFAULT CHARACTER SET utf8 ;
USE `BDD_INTER` ;

-- -----------------------------------------------------
-- Table `BDD_INTER`.`DataMeteos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDD_INTER`.`DataMeteos` ;

CREATE TABLE `DataMeteos` (
  `idDataMeteos` int(11) NOT NULL AUTO_INCREMENT,
  `TimeStamp` datetime DEFAULT NULL,
  `VitesseVent` int(11) DEFAULT NULL,
  `DirectionVent` int(11) DEFAULT NULL,
  `Pression` int(11) DEFAULT NULL,
  `Humidite` int(11) DEFAULT NULL,
  `PointRosee` int(11) DEFAULT NULL,
  `Pyra_N` int(11) DEFAULT NULL,
  `Pyra_E` int(11) DEFAULT NULL,
  `Pyra_S` int(11) DEFAULT NULL,
  `Pyra_O` int(11) DEFAULT NULL,
  `Luxmetre` int(11) DEFAULT NULL,
  `Temperature` float DEFAULT NULL,
  PRIMARY KEY (`idDataMeteos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



-- -----------------------------------------------------
-- Table `BDD_INTER`.`Locales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDD_INTER`.`Locales` ;

CREATE TABLE IF NOT EXISTS `BDD_INTER`.`Locales` (
  `idLocal` INT NOT NULL,
  `NomLocal` DATE NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_INTER`.`EvenFenetre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDD_INTER`.`EvenFenetre` ;

CREATE TABLE `EvenFenetre` (
  `idDataFenetre` int(11) NOT NULL AUTO_INCREMENT,
  `TimeStamp` datetime DEFAULT NULL,
  `EtatFenetre` tinyint(1) DEFAULT NULL,
  `NumeroFenetre` int(11) DEFAULT NULL,
  `Locales_idLocal` int(11) NOT NULL,
  PRIMARY KEY (`idDataFenetre`),
  KEY `fk_EvenFenetre_Locales1_idx` (`Locales_idLocal`),
  CONSTRAINT `fk_EvenFenetre_Locales1` FOREIGN KEY (`Locales_idLocal`) REFERENCES `Locales` (`idLocal`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `BDD_INTER`.`EvenLuminaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDD_INTER`.`EvenLuminaires` ;

CREATE TABLE IF NOT EXISTS `BDD_INTER`.`EvenLuminaires` (
  `idEvenLuminaires` INT NOT NULL AUTO_INCREMENT,
  `TimeStamp` DATETIME NULL,
  `EtatLuminaires` TINYINT(1) NULL,
  `NumeroLuminaire` INT(11) NULL,
  `Locales_idLocal` INT NOT NULL,
  PRIMARY KEY (`idEvenLuminaires`),
  INDEX `fk_EvenLuminaires_Locales1_idx` (`Locales_idLocal` ASC),
  CONSTRAINT `fk_EvenLuminaires_Locales1`
    FOREIGN KEY (`Locales_idLocal`)
    REFERENCES `BDD_INTER`.`Locales` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDD_INTER`.`Temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDD_INTER`.`Temperature` ;


CREATE TABLE `Temperature` (
  `idEvenTemperature` int(11) NOT NULL AUTO_INCREMENT,
  `TimeStamp` datetime DEFAULT NULL,
  `Temperature` float DEFAULT NULL,
  `Hygro` float DEFAULT NULL,
  `Locales_idLocal` int(11) NOT NULL,
  PRIMARY KEY (`idEvenTemperature`),
  KEY `fk_EvenTemperature_Locales1_idx` (`Locales_idLocal`),
  CONSTRAINT `fk_EvenTemperature_Locales1` FOREIGN KEY (`Locales_idLocal`) REFERENCES `Locales` (`idLocal`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BDD_INTER`.`Locales`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDD_INTER`;


ALTER TABLE `BDD_INTER`.`Locales` CHANGE COLUMN `NomLocal` `NomLocal` VARCHAR(11) NULL DEFAULT NULL ;
ALTER TABLE `BDD_INTER`.`DataMeteos` CHANGE COLUMN `TimeStamp` `TimeStamp` DATETIME NULL DEFAULT NULL ;
ALTER TABLE `BDD_INTER`.`EvenFenetre` CHANGE COLUMN `TimeStamp` `TimeStamp` DATETIME NULL DEFAULT NULL ;


INSERT INTO `BDD_INTER`.`Locales` (`idLocal`, `NomLocal`) VALUES (1, 'Teslab');
INSERT INTO `BDD_INTER`.`Locales` (`idLocal`, `NomLocal`) VALUES (2, 'Turing');
INSERT INTO `BDD_INTER`.`Locales` (`idLocal`, `NomLocal`) VALUES (3, 'Lumieres');
INSERT INTO `BDD_INTER`.`Locales` (`idLocal`, `NomLocal`) VALUES (4, 'Nobel');
INSERT INTO `BDD_INTER`.`Locales` (`idLocal`, `NomLocal`) VALUES (5, 'Hall');

COMMIT;

